default_platform(:ios)

platform :ios do
  desc "Build all Swift Packages"
  lane :build_all_packages do
    products = ["ApiClient", "ConfirmationAlert", "Models", "MyRidesFeature", "StyleSheet"]
    products.each do |product|
      sh "xcodebuild -scheme '#{product}' -destination 'generic/platform=iOS' clean build | xcpretty"
    end
  end

  desc "Run Tests for all Swift Packages"
  lane :run_all_tests do
    products = ["ApiClient", "ConfirmationAlert", "Models", "MyRidesFeature", "StyleSheet"]
    products.each do |product|
      sh "xcodebuild -scheme '#{product}' -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean test | xcpretty"
    end
  end

  desc "Generate Documentation for all Swift Packages"
  lane :generate_all_docs do
    products = ["ApiClient", "ConfirmationAlert", "Models", "MyRidesFeature", "StyleSheet"]
    products.each do |product|
      sh "xcodebuild docbuild -scheme '#{product}' -destination 'generic/platform=iOS' -derivedDataPath ./build/#{product} | xcpretty"
    end
  end

  desc "Build, Test, and Generate Documentation for all Swift Packages"
  lane :build_test_and_document_all do
    build_all_packages
    run_all_tests
    generate_all_docs
  end
end
